name: Golf Clash Notebook
baseurl: ''
description: An Open Source Guide to Mastering Golf Clash
highlighter: rouge
docs: true
collections:
  tut:
    output: true
sass:
  load_paths:
  - _sass
  - css
  style: compressed
version: 0.1.0-SNAPSHOT
org: Golf Clash Notebook
page_gen-dirs: true
page_gen:
- name: course-name
  data: courses
  dir: courses
  template: _includes/courses/individual-template.liquid
  index_files: true
- name: course-name
  data: courses
  dir: courses/notesheets
  template: _includes/courses/notes-template.liquid
  index_files: true
- name: number
  data: tours
  dir: tours
  template: _includes/tours/individual-template.liquid
  index_files: true
- name: tournament-name
  data: tournaments
  dir: tournaments
  template: _includes/tournaments/individual-template.liquid
  index_files: true
- name: tournament-name
  data: tournaments
  dir: tournaments/notesheets
  template: _includes/tournaments/notes-template.liquid
  index_files: true
- name: number
  data: courses.Christmas.holes
  dir: courses/Christmas
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.CreepyCliffs.holes
  dir: courses/CreepyCliffs
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.GlenmonarchEstate.holes
  dir: courses/GlenmonarchEstate
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.GokashoBay.holes
  dir: courses/GokashoBay
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.GreenochPoint.holes
  dir: courses/GreenochPoint
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.HauntedHills.holes
  dir: courses/HauntedHills
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.JuniperPoint.holes
  dir: courses/JuniperPoint
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.MeadowCastle.holes
  dir: courses/MeadowCastle
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.NamhaeCliffs.holes
  dir: courses/NamhaeCliffs
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.SakuraHills.holes
  dir: courses/SakuraHills
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.SantaVentura.holes
  dir: courses/SantaVentura
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.SouthernPines.holes
  dir: courses/SouthernPines
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.SunshineGlades.holes
  dir: courses/SunshineGlades
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.TheMilano.holes
  dir: courses/TheMilano
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.TheOasis.holes
  dir: courses/TheOasis
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.VineyardAcres.holes
  dir: courses/VineyardAcres
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: courses.WinterLinks.holes
  dir: courses/WinterLinks
  template: _includes/courses/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.AsiaPacific.holes
  dir: tournaments/AsiaPacific
  extra:
    tournament-name: Asia Pacific
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.WestCoast.holes
  dir: tournaments/WestCoast
  extra:
    tournament-name: West Coast
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.4thOfJuly.holes
  dir: tournaments/4thOfJuly
  extra:
    tournament-name: 4th Of July
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.UKChampions.holes
  dir: tournaments/UKChampions
  extra:
    tournament-name: UK Champions
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.SunshineOpen.holes
  dir: tournaments/SunshineOpen
  extra:
    tournament-name: Sunshine Open
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.SakuraClassic.holes
  dir: tournaments/SakuraClassic
  extra:
    tournament-name: Sakura Classic
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.LaborDay.holes
  dir: tournaments/LaborDay
  extra:
    tournament-name: Labor Day
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.WineValley.holes
  dir: tournaments/WineValley
  extra:
    tournament-name: Wine Valley
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.HauntedHills.holes
  dir: tournaments/HauntedHills
  extra:
    tournament-name: Haunted Hills
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.CreepyCliffs.holes
  dir: tournaments/CreepyCliffs
  extra:
    tournament-name: Creepy Cliffs
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.CaliforniaClassic.holes
  dir: tournaments/CaliforniaClassic
  extra:
    tournament-name: California Classic
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.Thanksgiving.holes
  dir: tournaments/Thanksgiving
  extra:
    tournament-name: Thanksgiving
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.WinterLinks.holes
  dir: tournaments/WinterLinks
  extra:
    tournament-name: Winter Links
  template: _includes/tournaments/hole-template.liquid
  index_files: true
- name: number
  data: tournaments.Christmas.holes
  dir: tournaments/Christmas
  extra:
    tournament-name: Christmas
  template: _includes/tournaments/hole-template.liquid
  index_files: true
markdown: kramdown
